title: Behavioral Ecology Laboratory KOPRI
description: Behavioral Ecology Laboratory from Korea Research Institute

url: http://chani3218.github.io/
baseurl: "/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 3

navigation:
  - title: Home
    url: /index.html
  - title: Research
    url: /research
  - title: Members
    url: /members
  - title: Publications
    url: /publications
  - title: Gallery
    url: /gallery
  - title: Contact
    url: /contact

social:
   twitter: gentoo210
   email: wonyounglee@kopri.re.kr
 
google_analytics: "UA-58263416-1"

disqus:
    shortname: 
